consumes:
- application/json
info:
  description: Platform for creating and using A/B testing experiments
  title: lABoratory
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"
